### PR TITLE
CurrentFDD

### PR DESCRIPTION
**Pull request by EMostafaAli**
* Implement current fdd that returns Federation FOM in XML format

I implemented this in StringRender Class (not sure if this the right place). I need guidance on how to reach this from MomFederation Class (which contains getcurrentfdd method)

### CODE REVIEW

**Comment by michaelrfraser** [comment]
Hi there @EMostafaAli,

It looks like your editor has completely changed the indenting or line endings of the StringRenderer file. The diff is showing that the file has completely changed, and as such I'm having a hard time working out what has changed with the commit.

Can you please reformat the file back to its original indenting/line ending policy and recommit?

**Comment by EMostafaAli** [comment]
Line ending was the culprit, hope this is better.

Again,  I need guidance on how to reach this from MomFederation Class (which contains getcurrentfdd method)

**Comment by EMostafaAli** [comment]
Just checking, if you are planning to review this anytime soon.
Thanks,

**Comment by michaelrfraser** [comment]
Hi there @EMostafaAli. Firstly apologies about the wait. We've been running from one deadline to another in our commercial work so just finding time now to check out your PR.

With respect to the code, everything looks great. Rather than merging the PR on its own, would you mind if I took the code you've written, and combined it with @bShibby's PR here https://github.com/openlvc/portico/pull/262? He's also implemented a mechanism to dump the in-memory FOM to XML for the purposes of communicating the datatypes to the C++ interface.

Your implementation looks to be more complete, however I would prefer it to live in its own class rather than the StringRenderer class as @bShibby has done (He's used XmlRenderer). I think it'd be worth merging the two, rather than having two separate implementations.

**Comment by EMostafaAli** [comment]
@michaelrfraser, No problem. Go ahead and merge it with the other PR.

**Comment by michaelrfraser** [comment]
Hi there @EMostafaAli I've taken your XML rendering routines and have pulled them into a new `XMLRenderer` class. The new class has been submitted in PR #271 (we're in the middle of re-engineering portico to a centralized model and with that we're supporting a range of new MOM attributes and interactions).

Thanks for your contribution! I will close off this PR once #271 has been accepted.

**Comment by michaelrfraser** [comment]
Work committed as per #271. Thanks for your contribution!

**Pull request closed without merging**
